#+title:      emacs-using-rimel-for-chinese-input-on-windows
#+date:       [2026-05-14 Thu 23:02]
#+filetags:   :blog:
#+identifier: 20260514T230246

[2026-05-14 Thursday 23:02]

#+begin_quote
This entire article is written using Emacs' built-in rimel input method + rime-frost scheme
#+end_quote

Chinese input in Emacs has always been an issue. Although we have the excellent [[https://github.com/laishulu/emacs-smart-input-source][sis]] that smoothly switches external input methods within Emacs, on Windows and macOS, external input methods always have some minor imperfections:

On Windows, the API for getting input method status seems problematic. Based on my experience with Squirrel (Weasel), when Squirrel switches Chinese/English input status in other programs, or when rime reloads, Emacs often remembers the previous state, forcing one to manually toggle Squirrel's Chinese/English state to match the sis state within Emacs.

On macOS, the problem is even more troublesome. The widely used Emacs-plus does not have a built-in input method switching API. Instead, the GUI Emacs Mac Port does, which has led me to use forum user [[https://github.com/LuciusChen/.emacs.d][Lucius's compilation script]] to patch Emacs-plus with input method switching functionality to work with sis.

Fortunately, Emacs can also call dynamic modules internally, giving rise to [[https://github.com/tumashu/pyim][pyim]], [[https://github.com/emacs-rime/liberime][liberime]], [[https://github.com/DogLooksGood/emacs-rime][emacs-rime]], and [[https://github.com/emacs-rime/rimel][rimel]] — Chinese input modules that fully utilize Emacs' built-in input functionality and [[https://github.com/rime/librime][librime]]. Among these, liberime is only used to provide a dynamic module that combines Emacs with the external librime.dll, so I won't include it in the comparison. For the remaining three, you can see a comparison [[https://github.com/emacs-rime/rimel#%E4%B8%8E-emacs-rimepyim-%E7%9A%84%E5%AF%B9%E6%AF%94][here]].

The reason I chose rimel is actually quite simple: it's relatively lightweight and theoretically easier to install. I once tried to install emacs-rime on Windows Emacs, but was ultimately discouraged by the need to compile dynamic modules.

* Installing and Configuring liberime and rimel
:PROPERTIES:
:CUSTOM_ID: h:c325fffd-458b-4160-ac3c-f8304bc6b7a5
:END:
Since both are on melpa and rimel depends on liberime, we only need to specify rimel when writing the use-package declaration:

#+begin_src elisp
(use-package rimel :ensure t
#+end_src

Then, refer to the documentation provided by rimel and liberime for configuration.

First, configure the DLL location for liberime and its related folders.
I put =liberime-core.dll= in the =~/.emacs.d/bin/= path for synchronization across multiple devices. The related dependency DLLs are also in the same location; we'll detail which ones need to be copied later.

#+begin_src elisp
  :custom
  (liberime-module-file "~/.emacs.d/bin/liberime-core.dll")
#+end_src

Then set two critical folder paths: =shared-data-dir= determines where rime configuration files are stored. Each time we start rimel, it reads the configuration from this folder and generates a final file for direct use in =user-data-dir=. Since the former may involve device-specific names in multi-device synchronization, it's best not to place either in cross-device sync folders; instead, find another location. I put them in the =~/emacs-local/= folder.

The former can be copied from the =/share/rime-data= directory in liberime's release.

  #+begin_src elisp
  (liberime-shared-data-dir "~/emacs-local/rime-data")
  (liberime-user-data-dir "~/emacs-local/rimel")
  #+end_src

Remember to configure the default input method as rimel:

  #+begin_src elisp
  (default-input-method "rimel")
  #+end_src

The following variable determines in which areas to automatically disable the input method and enter English mode:

  #+begin_src elisp
  ;; Recommended configuration: code region + after alphabet + uppercase letter
  (rimel-disable-predicates
      '(rimel-predicate-prog-in-code-p
        rimel-predicate-after-alphabet-char-p
        rimel-predicate-current-uppercase-letter-p))
  #+end_src

You could also add =rimel-predicate-org-in-src-block-p= here to automatically switch to English in source blocks. However, note that the =org-in-src-block-p= function it uses explicitly states that all blank lines after "end" are considered part of the source block.

  #+begin_quote
  Note that affiliated keywords and blank lines after are considered a part of a source block.
  #+end_quote

So use it based on your actual situation.

Use a popup frame to display candidates in the GUI:

#+begin_src elisp
;; Optional: use posframe to show candidates (posframe will be used by default if installed)
  (rimel-show-candidate 'posframe))
#+end_src

* Installing and Configuring DLLs

#+begin_quote
Note: Since I use the UCRT version of Windows Emacs, the following is based on that. Please select the corresponding DLL based on your Emacs version.
#+end_quote

Continuing from above, if you directly download the precompiled DLL package from liberime's [[https://github.com/emacs-rime/liberime/releases][release]] and put it in the =liberime-module-file= path mentioned earlier, you'll find it won't start.

Based on experimentation, this is because the precompiled package only contains =liberime.dll= and =librime-1.dll= in the =/bin= directory, missing the dependency files for these two DLLs.

The specific dependency files are as follows:

#+begin_example
libgcc_s_seh-1.dll
libgflags.dll
libglog-2.dll
libleveldb.dll
libmarisa-0.dll
libopencc-1.2.dll
libstdc++-6.dll
libunwind.dll
libwinpthread-1.dll
libyaml-cpp.dll
#+end_example

The easiest way is to download msys2, then install - configure mirror sources - update, install librime, and finally find the DLLs in the corresponding =version/bin= (for me it's =/ucrt/bin=) and copy them.

The second easiest way is to go to msys2's [[https://packages.msys2.org/packages/mingw-w64-x86_64-libunwind?repo=mingw64][package interface]], search for the needed file name, click the link after 「File:」, download and extract, find the corresponding DLL in =/bin=, and copy it to the =liberime-module-file= path specified earlier.

* Adjusting the rime Configuration Scheme

If you've successfully completed the above two steps, after restarting Emacs, press =C-\= and type a few keys; you should see candidates appear in the minibuffer or posframe. However, you may notice that the output is in Traditional Chinese. This is because the copied default uses the Plum Pinyin (明月拼音) scheme, which outputs Traditional Chinese by default. Fortunately, we can fully utilize rime's customization features to switch to our desired scheme.

But before you excitedly prepare to use various fancy schemes, I must remind you: since our liberime only uses librime, the widely used LUA script plugins and language model plugins (octagram) in many schemes cannot be used in liberime, requiring manual adjustment of the scheme.

As for which scheme to use, refer to rime-frost author's [[https://github.com/gaboolic/rime-schema-compare/blob/main/report/latest.md][rime-schema evaluation]], and focus on results that do not contain 「_with_gram」. According to the evaluation results from May 12, 2026, rime_frost has a sentence accuracy of 46.88%, character accuracy of 86.25%, and character accuracy (per-sentence average) of 84.87%, ranking among the top. Therefore, I'll use the rime-frost scheme as an example.

Download the latest scheme archive from rime-frost's [[https://github.com/gaboolic/rime-frost/releases][release]], extract it, copy all contents to replace the files in =shared-data-dir=, and directly modify the corresponding files in =shared-data-dir=.

** Modifying the Default Input Scheme
:PROPERTIES:
:CUSTOM_ID: h:ce635fc6-238c-4dcd-b8f0-387294f3d6e6
:END:
Although rimel suggests modifying the input scheme by changing the =rimel-schema= variable, practice shows this is unnecessary; simply modify =default.yaml= directly. Since I only use Xiaohe Shuangpin (Xiaohe Double Pinyin), I changed it to:

#+begin_src yaml
# Scheme list
schema_list:
  # You can directly delete or comment out unwanted schemes; the corresponding *.schema.yaml files can also be deleted
  - schema: rime_frost_double_pinyin_flypy    # Xiaohe Shuangpin
#+end_src

Then, go to your chosen scheme's configuration file; for me, it's =rime_frost_double_pinyin_flypy.schema.yaml=. Delete any parts related to lua, such as under =engine=, all lines starting with =lua_= must be deleted. My result after deletion is as follows:

#+begin_src yaml
# Input engine
engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@radical_lookup  # Component character decomposition custom tag
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator@frost_aux       # ` single-char aux lookup
    - script_translator
    - table_translator@custom_phrase    # Custom phrase custom_phrase.txt
    - table_translator@melt_eng         # English input
    - table_translator@cn_en            # Chinese-English mixed vocabulary
    - table_translator@radical_lookup   # Component character decomposition reverse lookup
  filters:
    - reverse_lookup_filter@radical_reverse_lookup  # Component character decomposition filter
    - simplifier@emoji                              # Emoji
    - simplifier@chaifen
    - simplifier@chaifen_all
    - simplifier@chinese_english
    - simplifier@traditionalize                     # Simplified/Traditional switching
    - simplifier@mars                               # Martian text
    - uniquifier                                    # Deduplication
#+end_src

** Some Personal Preference Optimizations
:PROPERTIES:
:CUSTOM_ID: h:4c8d6c4a-612d-4ef6-b322-487c8daf5e1f
:END:

Since screen real estate in Emacs is precious, I disabled the candidate pinyin annotation feature. Simply set =translator:= 's =comment_format:= to =- xform/.*//=.

When rimel starts, it seems to incorrectly compare =rimel-schema= with =(liberime-current-schema)= as strings, but the latter is not a valid function. We need to manually modify the =rimel-active= function, replacing:

#+begin_src emacs-lisp
(defun rimel-activate (_name)
  "Activate rimel input method.
Called by Emacs when user selects the \"rimel\" input method.
_NAME is the input method name (unused)."
  (unless (liberime-workable-p)
    (liberime-load))
  (when (and rimel-schema
             (liberime-workable-p)
             (not (string= rimel-schema (liberime-current-schema))))
    (liberime-try-select-schema rimel-schema))
  (setq-local input-method-function #'rimel-input-method)
  (setq-local deactivate-current-input-method-function #'rimel-deactivate))
#+end_src

with:

#+begin_src emacs-lisp
(defun rimel-activate (_name)
  "Activate rimel input method.
Called by Emacs when user selects the \"rimel\" input method.
_NAME is the input method name (unused)."
  (unless (liberime-workable-p)
    (liberime-load))
  (when (and rimel-schema
             (liberime-workable-p)
             (not (string= rimel-schema liberime-current-schema)))
    (liberime-try-select-schema rimel-schema))
  (setq-local input-method-function #'rimel-input-method)
  (setq-local deactivate-current-input-method-function #'rimel-deactivate))
#+end_src

The built-in =rimel-predicate-org-in-src-block-p= directly calls =org-in-src-block-p=, making it difficult to input Chinese after line breaks in source blocks. Let's create our own predicate function, removing the feature that skips line breaks and spaces:

#+begin_src emacs-lisp
(defun my/rimel-predicate-org-in-src-block-p ()
  "Return non-nil when point is inside an Org source block."
  (and (derived-mode-p 'org-mode)
       (fboundp 'org-in-src-block-p)
       (let ((element (org-element-at-point)))
         (when (org-element-type-p element 'src-block)
           (not (or (<= (line-beginning-position)
                        (org-element-post-affiliated element))
                    (>= (line-end-position)
                        (org-with-point-at (org-element-end element)
                          (point)))))))))

;; Add it in
(add-to-list 'rimel-disable-predicates 'my/rimel-predicate-org-in-src-block-p)
#+end_src

* Additional Notes

If you have everything configured but get an error when executing =liberime-load=, it may be a path loading issue. Consider adding the directory containing =liberime-module-file= to Windows' user environment variables, then restart your computer to reload the user environment variables, and then start Emacs again.

* Configuration File
:PROPERTIES:
:CUSTOM_ID: h:d17912fe-ec54-456a-986c-d5920f488a5b
:END:
#+begin_src emacs-lisp :exports both :results raw :eval no-export
(files--ensure-directory my/desktop-path)
(let ((file "rimel-config.txt"))
  (org-babel-tangle-file (buffer-file-name) (concat my/desktop-path file) "elisp")
  (format "[[https://blog.prayhand13013.top/%s][Click to view the above configuration code summary]]" file))
#+end_src

#+RESULTS:
[[https://blog.prayhand13013.top/rimel-config.txt][Click to view the above configuration code summary]]
