#+title:      emacs-enable-beancount-plugin-to-complete-payees
#+date:       [2026-01-21 Wed 22:42]
#+filetags:   :blog:
#+identifier: 20260121T224239

[2026-01-21 Wed 22:42]

Recently, with AI guidance, I updated my beancount bookkeeping model, switching from continuously creating sub-accounts to a model of top-level accounts + payee + narration. Since this is also the narration model recommended by beancount official, it works well with tools like fava to filter and match eligible transactions using payee and narration.

Note: A beancount transaction generally looks like this:
#+begin_src beancount
2026-01-21 * "Payee" "Narration"
  Account1   1 CNY
  Account2   -1 CNY
2026-01-21 * "Narration"
  Account1   1 CNY
  Account2   -1 CNY
#+end_src

However, by default, the official Emacs plugin =beancount.el= for beancount does not provide payee completion. (Of course, it also doesn't provide account completion from a specified file; by default, it only completes accounts in the current buffer. This can be solved by [[https://blog.prayhand13013.top/20250113T235551--emacs-%E8%AE%A9beancount%E6%8F%92%E4%BB%B6%E6%94%AF%E6%8C%81%E4%B8%AD%E6%96%87%E8%B4%A6%E6%88%B7%E5%90%8D__blog.html][this article]]).

** Payee Completion Code

If you want a function that can select a date and complete payees, and you already have beancount installed on your computer (you can call =bean-query=; if this command is not available, you can install =beanquery= via a package manager), you can refer to the following code (generated by LLM, tested and working):

[2026-03-08 Sun 23:55]: Updated to code that relies on regular expression matching, which is faster than =bean-query=.

#+begin_src elisp
(defvar my/beancount-payee-cache nil
  "Cache for payee list to improve completion speed.")
(defvar my/beancount-payee-files (append '("ADDITIONAL/BEAN/FILE") (directory-files "BEAN/FILE/DIRECTORY" t "bean"))
  "List of beancount record files '.bean'")
(defun my/beancount-refresh-payee-cache ()
  "Force refresh the Payee cache. Get Payee by traversing files with regex matching, no external bean-query required."
  (interactive)
  (message "Scanning payees from file list...")
  (let ((payee-set (make-hash-table :test 'equal)))
    (dolist (file-path my/beancount-payee-files)
      (when (file-exists-p file-path)
        (with-temp-buffer
          (insert-file-contents file-path)
          ;; Directly search for lines starting with a date and containing at least two double quotes (i.e., Payee and Narration)
          ;; Regex explanation: ^date +flag +\"(Payee)\" +\"(Narration)\"
          (while (re-search-forward "^[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\} [ *!] \"\\([^\"]+\\)\" \"\\([^\"]+\\)\"" nil t)
            (puthash (match-string 1) t payee-set)))))
    
    (setq my/beancount-payee-cache (sort (hash-table-keys payee-set) #'string<))
    (message "Payee cache refreshed, total %d items." (length my/beancount-payee-cache))
    my/beancount-payee-cache))
(defun my/beancount-get-payees-with-cache ()
  "Get the payee list. If the cache is empty, load it for the first time."
  (if my/beancount-payee-cache
      my/beancount-payee-cache
    (my/beancount-refresh-payee-cache)))
;; Use the calendar interface to select a date and quickly insert a beancount entry
(defun my/beancount-insert-chosen-date ()
   "Insert a Beancount-formatted date, Payee, and Narration.
Payee supports completion from historical records."
  (interactive)
  (let* (;; 1. Get the date (keep your original org-time-stamp logic)
         (date (substring
                (with-temp-buffer
                  (org-time-stamp nil nil)
                  (buffer-string))
                1 11))
         ;; 2. Get the Payee list for completion
         (payee-list (my/beancount-get-payees-with-cache))
         ;; 1. Input Payee
         (payee (completing-read "Payee: " payee-list))
         
         ;; 2. Input Narration
         (narration (read-string "Narration: ")))
    
    ;; Insert date and flag
    (insert date " * ")
    
    ;; Insert Payee and Narration
    ;; According to Beancount syntax: if both exist, the format is "Payee" "Narration"
    ;; If only one exists, it defaults to Narration
    (cond
     ((and (not (string-empty-p payee)) (not (string-empty-p narration)))
      (insert (format "\"%s\" \"%s\"" payee narration)))
     ((not (string-empty-p payee))
      (insert (format "\"%s\"" payee)))
     (t 
      (insert "\"\""))) ;; Insert empty quotes if both are empty
    
    ;; Newline and indent
    (insert "\n  ")))
#+end_src

Then configure beancount to use this function to replace the default =beancount-insert-date= keybinding =M-RET=

#+begin_src elisp
(use-package beancount
  :mode
  ("\\.bean\\(?:count\\)?\\'" . beancount-mode)
  :bind
  (:map beancount-mode-map
        ;; Bind a custom function for quickly inserting dates
        ("M-RET" . my/beancount-insert-chosen-date)))
#+end_src

** Usage Instructions

In a beancount file, such as =2026.bean=, press =M-RET=, and org-mode's date selection window will pop up. After selecting a date, you will be prompted to enter the payee (with completion), and then prompted to enter the narration. If the payee is not empty but the narration is empty, the string received from the payee will be used as the narration (beancount default behavior).
