# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Gen

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: CheckoutRepo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pyecharts pathlib pandas
    # - name: GetS1GeneralData
    #   uses: GuillaumeFalourd/clone-github-repo-action@v1
    #   with:
    #     owner: 'TomoeMami'
    #     repository: 'S1PlainTextGeneral'
    # - name: GetS1BackupData
    #   uses: actions/checkout@v2
    #   with:
    #     repository: TomoeMami/S1PlainTextBackup
    #     path: S1PlainTextBackup
    - name: AutoEcharts
      run: |
        python gen.py
    - name: Copy files to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'anime-2018.html anime-2019.html anime-2020.html anime-2021.html anime-2022.html game-2018.html game-2019.html game-2020.html game-2021.html game-2022.html index.html troll-2018.html troll-2019.html troll-2020.html troll-2021.html troll-2022.html vtb-2018.html vtb-2019.html vtb-2020.html vtb-2021.html vtb-2022.html'
        destination-username: 'TomoeMami'
        destination-branch: 'main'
        destination-repository: 'S1VtbStatic'
        commit-username: 'PushBot'
        commit-email: 'Fake@email.com'
    - name: commit
      env:
        TZ: 'CST-8'
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        git config --global user.email fake@email.com
        git config --global user.name PushBot
        datime=$(date "+%Y年%m月%d日 %H:%M")
        echo "git commit: 上传于 $datime"
        if [ -n "$(git status -s)" ];then
            git add .
            git commit -m "上传于 $datime" -a
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
